// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ThongKe.Data;

#nullable disable

namespace ThongKe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251016102139_create table cong bo 16_10")]
    partial class createtablecongbo16_10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThongKe.Entities.BieuMau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTieusJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("CotsJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViBaoCao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("DonViId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DonViNhanBaoCao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("HangsJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("KyBaoCao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int?>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NgayLapBieu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayNhanBaoCaoJSON")
                        .HasColumnType("CLOB");

                    b.Property<string>("NguoiLapBieu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PhienBanChiTieuId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SoBieuMau")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("SoThongTu")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenBieuMau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int?>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ThongTu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DonViId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("BieuMaus");
                });

            modelBuilder.Entity("ThongKe.Entities.ChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int?>("DonViId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhanTosJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int?>("PhienBanDanhMucId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenChiTieu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DonViId");

                    b.HasIndex("PhienBanDanhMucId");

                    b.HasIndex("TenChiTieu")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ChiTieus");
                });

            modelBuilder.Entity("ThongKe.Entities.ChiTieuDaNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiTieuId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DongDuLieuJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Nguon")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Ten")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChiTieuId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ChiTieuDaNhaps");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoDienTichCayHangNamKhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("DienTichGieoTrong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichThuHoach")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichUocTinhGieoTrong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichUocTinhThuHoach")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiCay")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoDienTichCayHangNamKhacs");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoDienTichCayLauNamChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("DienTichGieoTrong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichThuHoach")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichUocTinhGieoTrong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichUocTinhThuHoach")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiCay")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MuaVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoDienTichCayLauNamChinhs");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoDienTichLua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("DienTichGieoTrong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichThuHoach")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichUocTinhGieoTrong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichUocTinhThuHoach")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MuaVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("CongBoDienTichLuas");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoDienTichNuoiTrongThuySan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("DienTich")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DienTichUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiThuySanChinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MoiTruongNuoi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoDienTichNuoiTrongThuySans");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoNangSuatLua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MuaVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("NangSuatLua")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("NangSuatLuaUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoNangSuatLuas");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoSanLuongCayHangNamKhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiCay")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MuaVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("SanLuong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SanLuongUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoSanLuongCayHangNamKhacs");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoSanLuongCayLauNamChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiCay")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MuaVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("SanLuong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SanLuongUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoSanLuongCayLauNamChinhs");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoSanLuongLua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MuaVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("SanLuongLua")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SanLuongLuaUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoSanLuongLuas");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoSanLuongNuoiTrongThuySan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiThuySanChinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MoiTruongNuoi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("SanLuong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SanLuongUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoSanLuongNuoiTrongThuySans");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoSanLuongSanPhamChanNuoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quy")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("SanLuongChanNuoiKhac")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SanLuongThitHoi")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoSanLuongSanPhamChanNuois");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoSanLuongThuySanKhaiThac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiThuySanChinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("SanLuong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SanLuongUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoSanLuongThuySanKhaiThacs");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoSoLuongGiaSucGiaCam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoaiVatNuoi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SoLuongUocTinh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoSoLuongGiaSucGiaCams");
                });

            modelBuilder.Entity("ThongKe.Entities.CongBoXuatKhauNongSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DonViGiaTri")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DonViKhoiLuong")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("GiaTri")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("IsCongBo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("KhoiLuong")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("LoaiNongSan")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaQuocGiaVungLT")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nam")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenQuocGiaVungLT")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Thang")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CongBoXuatKhauNongSans");
                });

            modelBuilder.Entity("ThongKe.Entities.DanhMuc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChildrenMaKieu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.PrimitiveCollection<string>("ChildrenMaMucs")
                        .HasColumnType("NCLOB");

                    b.Property<long>("Created")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DanhSachsJSON")
                        .HasColumnType("NCLOB");

                    b.Property<string>("KyHieu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaKieu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MaMuc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nguon")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParentMaKieu")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ParentMaMuc")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("Stt")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenMuc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<long>("Updated")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("MaKieu");

                    b.HasIndex("MaMuc");

                    b.HasIndex("ParentMaKieu");

                    b.HasIndex("ParentMaMuc");

                    b.HasIndex("TenMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("ThongKe.Entities.DanhMucImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Created")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DanhMucsJSON")
                        .HasColumnType("NCLOB");

                    b.PrimitiveCollection<string>("MaKieuDanhMucs")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nguon")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParentMaKieu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParentMaMuc")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RowsType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("SoBanGhiCapNhat")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SoBanGhiLoi")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SoBanGhiThemMoi")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenPhienBan")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("Updated")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucImport");
                });

            modelBuilder.Entity("ThongKe.Entities.DanhMucPublish", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Created")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DanhMucMoRongsJSON")
                        .HasColumnType("NCLOB");

                    b.Property<string>("DanhMucsJSON")
                        .HasColumnType("NCLOB");

                    b.Property<int>("IsDraft")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsPublish")
                        .HasColumnType("NUMBER(10)");

                    b.PrimitiveCollection<string>("MaKieuDanhMucs")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("Published")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TenPhienBan")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("ThoiGianHetHan")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("Updated")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucPublish");
                });

            modelBuilder.Entity("ThongKe.Entities.DonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("MaDonVi")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MaDonVi")
                        .IsUnique()
                        .HasFilter("\"MaDonVi\" IS NOT NULL");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("DonVis");
                });

            modelBuilder.Entity("ThongKe.Entities.DuLieuBieuMau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BieuMauId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("BieuMauJSON")
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DongDuLieusJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("NguonDuLieu")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("BieuMauId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("DuLieuBieuMaus");
                });

            modelBuilder.Entity("ThongKe.Entities.DuLieuChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiTieuId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("Data")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int?>("ImportId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId10")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId2")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId3")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId4")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId5")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId6")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId7")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId8")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PhanToId9")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChiTieuId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ImportId");

                    b.HasIndex("PhanToId1");

                    b.HasIndex("PhanToId10");

                    b.HasIndex("PhanToId2");

                    b.HasIndex("PhanToId3");

                    b.HasIndex("PhanToId4");

                    b.HasIndex("PhanToId5");

                    b.HasIndex("PhanToId6");

                    b.HasIndex("PhanToId7");

                    b.HasIndex("PhanToId8");

                    b.HasIndex("PhanToId9");

                    b.ToTable("DuLieuChiTieus");
                });

            modelBuilder.Entity("ThongKe.Entities.KieuBangThongKe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTieusJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("HashingSchema")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime?>("LastTableCreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("PhienBanChiTieuId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TableName")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HashingSchema")
                        .IsUnique();

                    b.HasIndex("PhienBanChiTieuId");

                    b.HasIndex("TableName")
                        .IsUnique()
                        .HasFilter("\"TableName\" IS NOT NULL");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("KieuBangThongKes");
                });

            modelBuilder.Entity("ThongKe.Entities.KieuDanhMuc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string>("ChildrenMas")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("Created")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Format")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsClosed")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsOpen")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Ma")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NhomDanhMuc")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ParentMa")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TruongDuLieusJSON")
                        .HasColumnType("NCLOB");

                    b.Property<long>("Updated")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Ma");

                    b.HasIndex("NhomDanhMuc");

                    b.ToTable("KieuDanhMuc");
                });

            modelBuilder.Entity("ThongKe.Entities.LogAuth", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BrowserVersion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Content")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("Created")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsLogin")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsLogout")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("OSVersion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("LogAuth");
                });

            modelBuilder.Entity("ThongKe.Entities.PhienBanChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTieusJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("PhienBanDanhMucId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TenPhienBan")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PhienBanDanhMucId");

                    b.HasIndex("TrangThai");

                    b.ToTable("PhienBanChiTieus");
                });

            modelBuilder.Entity("ThongKe.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CountResetPassword")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long?>("CountResetPasswordTime")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("Created")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("DonViThongKeId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("IsInactive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("IsLocked")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsVerifyRegister")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("RefreshTokenExpiryTime")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("ResetPasswordExpiryTime")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("ResetPasswordGuid")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Scope")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TinhThanhId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
